mu3e_relval_basedir: "/Users/ursl/data/mu3e/relval"

mu3e_repo: "git@bitbucket.org:mu3e/mu3e"
mu3e_tag: "v6.5"
mu3e_dir: "mu3e"
make_jobs: 10

relink_script: "/Users/ursl/mu3e/mu3eanca/perl/relinkBinFiles"

run_id: 5461
n_events: 3000

sim_scenarios:
  - id: "cosmic_twolayer"
    sim_conf: "sim_cosmic.json"
    trirec_conf: "trirec_twolayer_cosmic.conf"
  - id: "cosmic_threelayer"
    sim_conf: "sim_cosmic.json"
    trirec_conf: "trirec_threelayer_cosmic.conf"
  - id: "conf8_twolayer"
    sim_conf: "bvr2026/sim_conf8.json"
    trirec_conf: "trirec_twolayer_beam.conf"
  - id: "conf18_twolayer"
    sim_conf: "bvr2026/sim_conf18.json"
    trirec_conf: "trirec_twolayer_beam.conf"
  - id: "conf18_threelayer"
    sim_conf: "bvr2026/sim_conf18.json"
    trirec_conf: "trirec_threelayer_beam.conf"

sim_output_tpl: "output/sim-{scenario}.root"
sort_output_tpl: "output/sort-{scenario}.root"
trirec_output_tpl: "output/trirec-{scenario}.root"
fillhist_output_tpl: "output/histograms-{scenario}.root"

cdb_dbconn: "/Users/ursl/data/mu3e/cdb/"
cdb_GT: "mcidealv6.5"
run_fill_histograms_exe: "/Users/ursl/macros/ana/mu3eanca/prompt/relval/ana/bin/runFillHistograms"
