mu3e_repo: git@bitbucket.org:mu3e/mu3e
mu3e_tag: master
mu3e_dir: mu3e
make_jobs: 20
sort_input_base: /Users/ursl/data/mu3e/run2025/raw
raw_input_layout: flat
run_block_digits: 3
trirec_output_tpl: output/trirec-{task}.root
marker_dir: markers
job_submit_mode: local
cdb_GT: mcidealv6.5
rereco_task_templates:
- action: midas_meta
  input_file_tpl: run{run:05d}.mid.lz4
rereco_tasks: []
mu3e_rereco_basedir: /Users/ursl/data/mu3e/rereco
relink_script: /Users/ursl/mu3e/mu3eanca/perl/relinkBinFiles
cdb_dbconn: http://mu3edb0/cdb/
