#!/bin/perl

# ----------------------------------------------------------------------
# g4bl-runAllTransport
# ====================
#
# NOTE: The output goes to /psi/home/langenegger/data/slurm/pioneer-g4bl/transport/
#
# options: -l     local running
#          -p 28  momentum choice
#
#
#
# Usage examples:
# cd /psi/home/langenegger/data/g4bl/pioneer-g4bl/pioneer/transport/
# g4bl-runTransport -p 65 -m muprod0002 -n iQSKv0 pi0002.i
# g4bl-runTransport -p 65 -m muprod0002 -n iQSKv1 -s 'QSK41cur=-24.075 QSK42cur=41.088 QSK43cur=-26.710' pi0004.i
# g4bl-runTransport -p 55 pi0001.i pi0002.i
# g4bl-runTransport [-l] -p 55 -n triplettoff -s sQSK41set=0.' pi0001.i
#
# History 2022/05/24 first shot
#         2022/05/30 allow setting g4bl parameters with -s
#         2022/05/31 no longer put g4bl parameters into filename, but count up 
#
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use File::Copy;
use Getopt::Std;

getopts('di:lm:n:p:s:');

my $run = "/psi/home/langenegger/mu3e/mu3eanca/slurm/run";

# -- provide particle identity 
if ($opt_i) {
    @ids = ();
    @ids = ($opt_i);
}

if (!$opt_p) {
    $opt_p = 28;
}

if (!$opt_n) {
    $opt_n = "std";
}

if (!$opt_m) {
    $opt_m = "muprod0003";
}

my $slurmcsh = "/psi/home/langenegger/mu3e/mu3eanca/slurm/slurm-g4bl-pioneer.csh"; 

my $settings = "STORAGE1 /psi/home/langenegger/data/slurm/pioneer-g4bl/transport/XXOUTPUTXX";
$settings   .= "%G4BLOUTPUTDIR .";
$settings   .= "%MOMENTUM $opt_p";
$settings   .= "%G4BLTRACKFILE p$opt_p-$opt_m-BLTrackFile2_PDGidXXOPTIDXX_DetEMuPiFromTarget.txt";
if ($opt_s) {
    $settings   .= "%SETTINGS \"$opt_s\" ";
}

for ($iloop = 0; $iloop <= $#ARGV; $iloop++) {
    # -- add particle ID based on steering file
    my $ipart = 211;
    my $steerCard = $ARGV[$iloop];
    if ($steerCard =~ /mu/) {
        $ipart = -13;
    }
    if ($steerCard =~ /all/) {
        $ipart = 0;
    }
    # -- add counter in case steerCard already exists
    my $sname;
    $sname = "p$opt_p-$opt_m-$opt_n-$steerCard";
    if (-e $sname) {
        my $cnt = 1;
        ($stest = $sname) =~ s/$opt_n/$opt_n-n$cnt/; 
        while (-e $stest) {
            $cnt++;
            ($stest = $sname) =~ s/$opt_n/$opt_n-n$cnt/; 
        }
        $sname = $stest;
    }
    $sname =~ s/\%//g;
    $sname =~ s/\s//g;
    (my $snnoi = $sname) =~ s/\.i$//;
    copy ("$steerCard", "$sname");
    ($jsettings = $settings) =~ s/PDGidXXOPTIDXX/PDGid$ipart/g;
    $jsettings =~ s/XXOUTPUTXX/$snnoi/g;
    print "run -c $slurmcsh -r \'$jsettings\' $sname\n"; 
    if ($opt_d) {
        print "  not submitting\n";
    } else {
        if ($opt_l) {
            system("$run -m local -c $slurmcsh -r \'$jsettings\' $sname &");
        } else {
            system("$run -c $slurmcsh -r \'$jsettings\' $sname");
        }
    }
}

