#! /usr/bin/perl

# ----------------------------------------------------------------------
# midasCount
# ==========
#
# Usage:   midasCount -f /data/experiment/mu3e/data/2024/datachallenge/data/raw/run05378.mid.lz4
# -----
#
# History
#         2024/05/22 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use File::Basename;
my $dirname = dirname(__FILE__);
if ($dirname eq ".") {
    $dirname = cwd();
}

use lib '/Users/ursl/mu3e/mu3eanca/mdc/scripts/local/lib/perl5/darwin-thread-multi-2level/';
use Compress::LZ4;

use Getopt::Std;
getopts('df:');

use Cwd;


print("$dirname/modules/Compress-LZ4-0.25/lib/Compress\n");

open(IN, "$opt_f") || die "midasCount: Cannot open $opt_f\n";
binmode IN;


my $compressed = '';
my $cnt = 0;
while (1) {
    my $success = read IN, $compressed, 1;
    my $deco    = decompress($compressed);
    $cnt++;
    $hex = sprintf("%X", $deco);
    print($hex);
    die $! if not defined $success;
    last if not $success;
    last if ($cnt > 200);
}

print("\n");
