#! /usr/bin/perl

# ----------------------------------------------------------------------
# pcrTransfer
# ===========
#
# Usage:   ~/mu3e/mu3eanca/mdc2023/scripts/pcrTransfer
#
#
# History
#         2025/04/01 update to 2025 data taking: change source and exclude everything except mid files
#         2024/01/18 update to 2024jan MDC
#         2023/09/13 change target directory
#         2023/09/12 migrated out from proCalRec
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------
use Cwd;
use File::Basename;

my $mu3ebeif = "129.129.143.120";

my $dir = getcwd;

use Getopt::Std;
getopts('n:t:');

# ----------------------------------------------------------------------
# -- default values
# ----------------------------------------------------------------------
# -- source data directory on mu3ebe (keep my directory, else all is transferred in one go)
#my $pcrMu3eBEDir = ".ursl/data";
#my $pcrMu3eBEDir = "/data1/datachallenge/data/";
my $pcrMu3eBEDir = "online/online";

# -- target data directory on merlin
#my $pcrDataDir   = "/data/experiment/mu3e/data/2024/datachallenge/data/raw";
my $pcrDataDir   = "/data/experiment/mu3e/data/2024/datachallenge/2025/raw";

while (1) {
    print(&prefix("pcrTransfer"),  "rsync --include='*.mid.*' --exclude='*' -avL mu3e\@$mu3ebeif:$pcrMu3eBEDir/ $pcrDataDir/\n");
    # -- Note
    #    o the trailing '/'
    #    o -L transform symlink into referent file/dir
    #    system("rsync -avL -e \"ssh mu3e\@mu3egw ssh\" mu3e\@mu3ebe:$pcrMu3eBEDir/ $pcrDataDir/");
    system("rsync --exclude='\*' --include='\*.mid.\*' -avL mu3e\@$mu3ebeif:$pcrMu3eBEDir/ $pcrDataDir/");
    sleep(100);
}

# ----------------------------------------------------------------------
sub prefix() {
    ($long) = @_;
    my $now = localtime;
    # -- fill up in case too short
    $long .= "                         ";
    $shorter = substr($long, 0, 15);
    return ($now . "/" . $shorter . "/ ");
}
