#! /bin/tcsh

../_build/mu3eTrirec/mu3eTrirec --cdb.globalTag=datav6.2=2025Beam --cdb.dbconn=/Users/ursl/data/mu3e/cdb --conf trirec_twolayer_beam.conf /Users/ursl/data/mu3e/run2025/sort/run06285-sorted.root --output output/mu3eTrirec_run6285.root ;
../_build/mu3eTrirec/mu3eTrirec --cdb.globalTag=datav6.2=2025Beam --cdb.dbconn=/Users/ursl/data/mu3e/cdb --conf trirec_twolayer_beam.conf /Users/ursl/data/mu3e/run2025/sort/run06286-sorted.root --output output/mu3eTrirec_run6286.root ;
../_build/mu3eTrirec/mu3eTrirec --cdb.globalTag=datav6.2=2025Beam --cdb.dbconn=/Users/ursl/data/mu3e/cdb --conf trirec_twolayer_beam.conf /Users/ursl/data/mu3e/run2025/sort/run06287-sorted.root --output output/mu3eTrirec_run6287.root ;
../_build/mu3eTrirec/mu3eTrirec --cdb.globalTag=datav6.2=2025Beam --cdb.dbconn=/Users/ursl/data/mu3e/cdb --conf trirec_twolayer_beam.conf /Users/ursl/data/mu3e/run2025/sort/run06292-sorted.root --output output/mu3eTrirec_run6292.root ;
../_build/mu3eTrirec/mu3eTrirec --cdb.globalTag=datav6.2=2025Beam --cdb.dbconn=/Users/ursl/data/mu3e/cdb --conf trirec_twolayer_beam.conf /Users/ursl/data/mu3e/run2025/sort/run06301-sorted.root --output output/mu3eTrirec_run6301.root ;