#! /usr/bin/perl

# ----------------------------------------------------------------------
# cpFilesFromGitDir
# ===================
#
# Usage: ./cpFiles -g gitdir
#
# History 2022/09/01 first shot
#         
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('dg:');

# -- current "project" for backup storage
my $basedir = `pwd`;
chop($basedir);

# -- where to get the files from 
my $gitdir = "/psi/home/langenegger/data/mu3e-4.6-smb";
if ($opt_g) {
    $gitdir = $opt_g;
} else {
    die("you must specify the argument  -g gitdir\n");
}

my @files = getFileList();

foreach $file (@files) {
    print("cp $gitdir/$file .\n");
    if (!$opt_d) {
        system("/bin/cp -a $gitdir/$file ."); # preserve time and do not follow symlinks
    }
}


# ----------------------------------------------------------------------
sub getFileList {
    chdir($gitdir);
    @git = `git st --porcelain`;
    chdir($basedir);
    @lfiles = ();
    foreach $file (@git) {
        chop($file);
        $file =~ s/\s*M\s//;
        $file =~ s/\?\?\s//;
        if ($file =~ /\/$/) {
        } else {
            push(@lfiles, $file)
        }
    }

    # -- debug
    if (0) {
        foreach $file (@lfiles) {
            print("$file\n")
        }
    }
    
    return @lfiles;
}
