#! /usr/bin/perl

# ----------------------------------------------------------------------
# getFiles
# ========
#
# Usage: ./getFiles -r user@remote:/path -p trirec-runXXXX.root -r 6234,6235,6236
#
# Options: -r user@remote:/path remote directory (with login) for data
#          -p pattern pattern to match
#          -r runlist runlist to get files from
#
# History 2025/06/24 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#

getopts('r:p:r:');

if ($opt_r eq "") {
    $opt_r = "langenegger\@merlin-l-001:/data/experiment/mu3e/data/2025/trirec/250621";
}

if ($opt_p eq "") {   
    $opt_p = "trirec-runXXXXX.root";
}

if ($opt_r eq "") {
    $opt_r = "6234";
}

@runlist = split(/,/, $opt_r);


foreach $run (@runlist) {
  my $file = $opt_p;
  my $srun = sprintf("%05d", $run);
  $file =~ s/XXXXX/$srun/;
  $cmd = "scp $opt_r/$file .";
  print $cmd;
#  $result = `$cmd`;
#  print $result;
}



