#! /usr/bin/perl

# ----------------------------------------------------------------------
# getFiles
# ========
#
# Usage: ./getFiles -s user@remote:/path -p trirec-runXXXX.root -r 6234,6235,6236
#
# Options: -s user@remote:/path source directory on remote machine (with login) for data
#          -p pattern pattern to match
#          -r runlist runlist to get files from
#
# History 2025/06/24 first shot
#         2025/06/25 allow also no leading '0'
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;


getopts('r:p:s:');

if ($opt_s eq "") {
    $opt_s = "langenegger\@merlin-l-001:/data/experiment/mu3e/data/2025/trirec/250621";
}

if ($opt_p eq "") {   
    $opt_p = "trirec-runXXXXX.root";
}

if ($opt_r eq "") {
    $opt_r = "6111";
}

@runlist = split(/,/, $opt_r);


foreach $run (@runlist) {
  my $file = $opt_p;
  my $srun = sprintf("%05d", $run);
  if ($opt_p =~ /XXXXX/) {
    $file =~ s/XXXXX/$srun/;
  } elsif ($opt_p =~ /XXXX/) {
    $file =~ s/XXXX/$run/;
  }
  $cmd = "scp $opt_s/$file .";
  print "$cmd\n";
  system($cmd);
}



