#! /usr/bin/perl


# @tag = `ssh mu3eswitch0 'cd /home/mu3e/pixel-maskfiles && git status && cd -'`;
#$tag[0] = substr $tag[0], 0, -1;

@tag = `ssh mu3eswitch0 'cd /home/mu3e/pixel-maskfiles && git rev-parse HEAD && cd -'`;
$githash = substr $tag[0], 0, -1;

print "githash ->$githash<-\n";

exit(0);

$MAXCHIPS = 2; 

open(OUT, "| odbedit ") || die "Cannot open odbedit\n";
print OUT " cd /Equipment/PixelsCentral/Settings/TDACS \r\n";
print OUT " ls \r\n";

for ($i = 0; $i < $MAXCHIPS; $i++) {
    print OUT "set $i/TDACFILE /home/mu3e/pixel-maskfiles/noiseMaskFile-chipID$i \r\n";
}

print OUT "set GitHash $githash \r\n";


print OUT " quit \r\n";


close OUT;
