#! /usr/bin/perl

# ----------------------------------------------------------------------
# pixelNoiseMaskFiles
# ===================
#
# Usage: ./pixelNoiseMaskFiles [-N -n noiseMaskFile-chipID] [-T]
#
# Options: -N           change the names of the files
#          -n namestub  provide name stub
#          -T           write tag (obtained via ssh into switch0) into ODB key GitHash
#          -d           debug: do not ssh and do not interact with ODB
#
# History 2022/05/20 first shot
#         2022/05/23 add -N
#         2022/06/22 obtain hash of currently checked out commit, not HEAD
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
getopts('dNn:T');

my $midasdir = "/Equipment/PixelsCentral/Settings/TDACS";
my $tagName = "GitHash";


my $namestub = "/home/mu3e/pixel-maskfiles/noiseMaskFile-chipID";
if ($opt_n) {
    $namestub = $opt_n; 
}

# @tag = `ssh mu3eswitch0 'cd /home/mu3e/pixel-maskfiles && git status && cd -'`;
#$tag[0] = substr $tag[0], 0, -1;


$MAXCHIPS = 120; 
my $OUT;

if (!$opt_d) {
    open(OUT, "| odbedit ") || die "Cannot open odbedit\n";
    select OUT;
} else {
#    open(OUT, ">STDOUT"); # FIXME!!!
#    print " would be in ODB \r\n";
}

print " cd $midasdir \r\n";
print " ls \r\n";

if ($opt_N) {
    for ($i = 0; $i < $MAXCHIPS; $i++) {
        print "set $i/TDACFILE $namestub$i \r\n";
    }
}

if ($opt_T) {
    if (!$opt_d) {
#        @tag = `ssh mu3eswitch0 'cd /home/mu3e/pixel-maskfiles && git rev-parse HEAD && cd -'`;
        @tag = `ssh mu3eswitch0 'cd /home/mu3e/pixel-maskfiles && git --no-pager show --pretty=%H -s && cd -'`;
        $githash = substr $tag[0], 0, -1;
    }
    print "set GitHash $githash \r\n";
}



print " quit \r\n";


close OUT;
