#! /usr/bin/perl

# ----------------------------------------------------------------------
# portionRunList
# ==============
#           
# Usage:   cd .../mu3eanca/perl
#          portionRunList [-b] -f filename -n numOnLine -m numInBlock -r 123,124,125,..
#
# Options:
#   -b            Use block-based grouping instead of thousand-based grouping.
#                 When -b is NOT provided (default), a new block starts when
#                 the run number crosses a 1000 boundary (e.g., 999->1000, 1999->2000).
#                 When -b IS provided, blocks are created every numInBlock lines.
#
#   -f            filename  Output filename (default: "portionRunList.txt")
#
#   -n            numOnLine Number of runs per line (default: 10)
#
#   -m numInBlock Number of lines per block when using -b option (default: 10)
#                 Note: This option only applies when -b is used.
#
#   -r runlist    Comma-separated list of run numbers (required)
#                 Example: -r 123,124,125,126,127
#
# For large run ranges, you likely have to first paste into a file:
#          portionRunList -r `cat ~/bla`
#
# Examples:
#   # Default behavior: blocks start at thousand boundaries
#   portionRunList -r 999,1000,1001,1999,2000,2001
#
#   # Use block-based grouping (every 10 lines)
#   portionRunList -b -r 123,124,125,... -m 10
#
# History 
#         2025/12/22 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------

use Getopt::Std;
use File::Basename;

getopts('bf:m:n:r:');


print "portionRunList executed at ". localtime, "\n";

my $filename = "portionRunList.txt";
if ($opt_f) {
    $filename = $opt_f;
}

my $numOnLine = 10; 
if ($opt_n) {
    $numOnLine = $opt_n;
}

my $numInBlock = 10;
if ($opt_m) {
    $numInBlock = $opt_m;
}

my @runlist = "";
if ($opt_r) {
    @runlist = split(/,/, $opt_r);
} else {
    print "no run list, nothing to do. Exiting ... \n";
    exit(0);
}

open(OUT, ">$filename") || die "portionRunList: Cannot open $filename\n";

my $i = 1;
my $block = 0;
my $prevThousand = -1;
foreach $run (@runlist) {
    # Check if we should start a new block
    my $startNewBlock = 0;
    
    if (!$opt_b) {
        # Default mode: check for thousand change OR block length limit
        my $currentThousand = int($run / 1000);
        if ($prevThousand >= 0 && $currentThousand != $prevThousand) {
            # Start new block when thousand changes
            $startNewBlock = 1;
        }
        $prevThousand = $currentThousand;
        
        # Also check block length limit
        if ($block > 0 && ($block % $numInBlock == 0)) {
            $startNewBlock = 1;
        }
    } else {
        # Block-based mode: only check block length limit
        if ($block > 0 && ($block % $numInBlock == 0)) {
            $startNewBlock = 1;
        }
    }
    
    if ($startNewBlock) {
        print OUT "\n\n";
        $block = 0;
    }
    
    print OUT "$run,";
    if ($i > 0 && ($i % $numOnLine == 0)) {
        print OUT "\n";
        $block++;
    }
    $i++;
}
print OUT "\n";

close(OUT);

print "Run list written to $filename\n";