#! /usr/bin/perl

# ----------------------------------------------------------------------
# linkAllFilesRun
# ===============
#
# Usage:   ~/.ursl/mu3eanca/mdc2023/scripts/linkAllFilesRun -d /data1/datachallenge/data -r run04
#
#
# History
#         2024/01/18 adapt to data challenge 2024
#         2023/08/11 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------
use Cwd;
use File::Basename;

use Getopt::Std;
getopts('d:r:');

my @files  = glob("$opt_d/$opt_r*");

foreach $file (@files) {
    my($barefile, $directories) = fileparse($file);
    print("ln -s $file $barefile\n");
    symlink("$file", "$barefile");
}
