#! /usr/bin/perl

# ----------------------------------------------------------------------
# proCalRec
# =========
#
# Usage:   ~/mu3e/mu3eanca/mdc2023/scripts/proCalRec
#
#
# History
#         2023/08/11 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------
use Cwd;
my $dir = getcwd;

use Getopt::Std;
getopts('');

# -- default values
my $pcrBaseDir   = "/psi/home/langenegger/data/mdc2023";
my $pcrMu3eBEDir = ".ursl/data";
my $pcrDataDir   = "/psi/home/langenegger/data/mdc2023/data";
my $pcrExe       = "/psi/home/langenegger/mu3e/analyzer/_build/analyzer/analyzer_mu3e";
my $pcrConfig    = "/psi/home/langenegger/mu3e/analyzer/analyzer/config/";
my $pcrMidasDir  = "/data/experiment/mu3e/data/2022/raw/";

while (1) {
    &pcrTransfer();
    sleep(4);
}


# ----------------------------------------------------------------------
sub pcrTransfer() {
    print "callTransfer\n";
    # -- Note the trailing '/' 
    system("rsync -av -e \"ssh mu3e\@mu3egw ssh\" mu3e\@mu3ebe:$pcrMu3eBEDir/ $pcrDataDir/");
}
