#! /usr/bin/perl

# ----------------------------------------------------------------------
# prSv
# ====
#
# Usage:   ~/mu3e/mu3eanca/mdc2023/scripts/prSv
#
#
# History
#         2023/08/11 first shot
# ----------------------------------------------------------------------
# Send all questions, wishes and complaints to the 
#
# Author    Urs Langenegger <urslangenegger@gmail.com>
# ----------------------------------------------------------------------
use Cwd;
my $dir = getcwd;

use Getopt::Std;
getopts('');

# -- default values
my $prBaseDir  = "/psi/home/langenegger/data/mdc2023";
my $prExe      = "/psi/home/langenegger/mu3e/analyzer/_build/analyzer/analyzer_mu3e";
my $prConfig   = "/psi/home/langenegger/mu3e/analyzer/analyzer/config/";
my $prMidasDir = "/data/experiment/mu3e/data/2022/raw/";

